### PR TITLE
Fix bool side effect #372

### LINKED ISSUE #372: Side-effect reassignment of boolean variable
On release 1.1.0, a boolean variable may change its value after being used on the right hand side of an assignment, as in the below code:
```
def f()
 a=false
 print(a)
 b=true||a
 print(a)
end

f()
```
The `def` block may be swapped with an `if` or `for` block, but the issue goes away if the code happens outside of a block. The issue also goes away if `b=true||a` is replaced with `b=a||true`.

### PR DESCRIPTION
**Pull request by s-hadinger**
Fix #372

### CODE REVIEW

File: src/be_code.c [hunk 1]
```diff
@@ -472,7 +472,18 @@ static int exp2reg(bfuncinfo *finfo, bexpdesc *e, int dst)
...
         int pct = NO_JUMP;  /* position of an eventual LOAD true */
         int jpt = appendjump(finfo, jumpboolop(e, 1), e);
-        reg = e->v.idx;
+        /* below is a simplified version of `codedestreg` for a single bexpdesc */
+        if (e->type == ETREG) {
+            /* if e is already ETREG from local calculation, we reuse the register */
+            reg = e->v.idx;
+        } else {
+            /* otherwise, we allocate a new register or use the target provided */
+            if (dst < 0) {
```
Comment (skiars) [inline src/be_code.c]: Using the conditional expression `? :` should be better?

Comment (s-hadinger) [reply src/be_code.c]: Sure, done

**Comment by s-hadinger** [comment]
@skiars can you please approve? I can't merge otherwise

**Review by skiars — APPROVED** [review]
